import axios from "axios";
import Head from "next/head";
import type { NextPage, GetServerSidePropsContext } from "next";
import HomeComponent from "@/components/home/HomeComponent";

interface CurrencyHistory {
  date: string;
  open: string;
  high: string;
  low: string;
  close: string;
}

interface Info {
  "1. open": string;
  "2. high": string;
  "3. low": string;
  "4. close": string;
}

interface HomePageProps {
  pair: string;
  currencyHistory: CurrencyHistory[];
  error?: string;
}

const HomePage: NextPage<HomePageProps> = ({
  pair,
  currencyHistory,
  error,
}) => {
  return (
    <>
      <Head>
        <title>Cicada Challenge</title>
        <meta name="description" content="Generated by create NextJS" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <HomeComponent
        pair={pair}
        currencyHistory={currencyHistory}
        error={error}
      />
    </>
  );
};

export default HomePage;

const ALLOWED_CURRENCY_PAIRS = ["USDMXN", "EURUSD", "EURCHF", "CHFMXN"];

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { pair } = context.query;
  try {
    if (!pair || typeof pair !== "string") {
      throw new Error("Pleas select currency pair");
    }
    if (!ALLOWED_CURRENCY_PAIRS.includes(pair)) {
      throw new Error("Pleas select a valid currency pair");
    }
    const { data: currencyHistory } = await axios.get(
      `http://67.205.189.142:8000/historic-data/${pair}`
    );
    const parsedCurrencyHistory = Object.entries(
      currencyHistory["Time Series FX (Daily)"]
    )
      .map(([date, info]) => {
        if (typeof info === "object" && info !== null) {
          const typedInfo = info as Info;
          return {
            date,
            open: typedInfo["1. open"],
            high: typedInfo["2. high"],
            low: typedInfo["3. low"],
            close: typedInfo["4. close"],
          };
        }
        return null;
      })
      .filter((item) => item !== null) as CurrencyHistory[];
    return {
      props: {
        currencyHistory: parsedCurrencyHistory,
        pair,
      },
    };
  } catch (error: any) {
    if (pair === "CHFMXN") {
      return {
        props: {
          error: "The currency pair CHFMXN is not available at this time.",
          pair,
        },
      };
    } else {
      return {
        props: {
          error: error.message,
        },
      };
    }
  }
}
