import axios from "axios";
import Head from "next/head";
import type { NextPage, GetServerSidePropsContext } from "next";
import HomeComponent from "@/components/home/HomeComponent";
import CurrencyExchange from "@/components/home/currency/currencyExchange/CurrencyExchange";

interface CurrencyHistory {
  date: string;
  open: string;
  high: string;
  low: string;
  close: string;
}

interface Info {
  "1. open": string;
  "2. high": string;
  "3. low": string;
  "4. close": string;
}

interface HomePageProps {
  pair: string;
  currencyHistory: CurrencyHistory[];
}

const HomePage: NextPage<HomePageProps> = ({ pair, currencyHistory }) => {
  return (
    <>
      <Head>
        <title>Cicada Challenge</title>
        <meta name="description" content="Generated by create Luis Rangel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HomeComponent pair={pair} currencyHistory={currencyHistory} />
    </>
  );
};

export default HomePage;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { pair } = context.query;
  if (pair && typeof pair === "string" && (pair === "USDMXN" || pair === "EURUSD" || pair === "EURCHF") ) {
    const { data: currencyHistory } = await axios(
      `http://67.205.189.142:8000/historic-data/${pair}`
    );
    const parsedCurrencyHistory = Object.entries(
      currencyHistory["Time Series FX (Daily)"]
    )
      .map(([date, info]) => {
        if (typeof info === "object" && info !== null) {
          const typedInfo = info as Info;
          return {
            date,
            open: typedInfo["1. open"],
            high: typedInfo["2. high"],
            low: typedInfo["3. low"],
            close: typedInfo["4. close"],
          };
        }
        return null;
      })
      .filter((item) => item !== null) as CurrencyHistory[];
    return {
      props: {
        currencyHistory: parsedCurrencyHistory,
        pair,
      },
    };
  }
  return {
    props: {
      pair: "",
      currencyHistory: [],
    },
  };
}
